# 🕋 Auto Makah — Document Generator
# XLSX · DOCX · PPTX · PDF (HTML→print)

import os
import json
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

# ─── XLSX ─────────────────────────────────────────────────
def generate_xlsx(title: str, headers: list, rows: list, sheet_name: str = "Sheet1") -> str:
    """Generate an Excel file. Returns file path."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name

    # Title row
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(headers))
    ws["A1"] = title
    ws["A1"].font = Font(name="Arial", size=14, bold=True, color="1F4E79")
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 30

    # Headers
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=3, column=col, value=h)
        cell.font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Data
    for r, row in enumerate(rows, 4):
        for c, val in enumerate(row, 1):
            ws.cell(row=r, column=c, value=val).alignment = Alignment(horizontal="center")

    # Column widths
    from openpyxl.utils import get_column_letter
    from openpyxl.cell.cell import MergedCell
    for col_idx in range(1, len(headers) + 1):
        col_letter = get_column_letter(col_idx)
        max_len = 8
        for row in range(1, len(rows) + 5):
            cell = ws[f"{col_letter}{row}"]
            if not isinstance(cell, MergedCell) and cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 4, 40)

    path = _save_file(title, ".xlsx")
    wb.save(path)
    return path


# ─── DOCX ─────────────────────────────────────────────────
def generate_docx(title: str, sections: list) -> str:
    """Generate a Word document. sections = [{"heading": "...", "body": "..."}]"""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    h = doc.add_heading(title, 0)
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for sec in sections:
        doc.add_heading(sec.get("heading", ""), level=2)
        doc.add_paragraph(sec.get("body", ""))

    # Footer
    doc.add_paragraph(f"\nGenerated by Auto Makah 🕋 | {datetime.utcnow().strftime('%Y-%m-%d')}")

    path = _save_file(title, ".docx")
    doc.save(path)
    return path


# ─── PPTX ─────────────────────────────────────────────────
def generate_pptx(title: str, slides: list) -> str:
    """Generate a PowerPoint. slides = [{"title": "...", "content": "..."}]"""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = f"Auto Makah 🕋 | {datetime.utcnow().strftime('%Y-%m-%d')}"

    # Content slides
    for s in slides:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = s.get("title", "")
        if slide.placeholders[1]:
            slide.placeholders[1].text = s.get("content", "")

    path = _save_file(title, ".pptx")
    prs.save(path)
    return path


# ─── PDF (HTML) ───────────────────────────────────────────
def generate_pdf_html(title: str, sections: list, lang: str = "ar") -> str:
    """Generate a print-ready HTML page that can be saved as PDF."""
    dir_attr = 'dir="rtl"' if lang == "ar" else 'dir="ltr"'
    
    html = f"""<!DOCTYPE html>
<html {dir_attr}>
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  body {{ font-family: 'Segoe UI', Tahoma, Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a1a; line-height: 1.8; }}
  h1 {{ color: #1F4E79; border-bottom: 3px solid #1F4E79; padding-bottom: 10px; }}
  h2 {{ color: #2E75B6; margin-top: 30px; }}
  .section {{ margin-bottom: 25px; }}
  .footer {{ margin-top: 40px; padding-top: 15px; border-top: 1px solid #ddd; color: #666; font-size: 0.85em; }}
  @media print {{ body {{ margin: 20px; }} }}
</style>
</head>
<body>
<h1>{title}</h1>
"""
    for sec in sections:
        html += f'<div class="section"><h2>{sec.get("heading", "")}</h2><p>{sec.get("body", "")}</p></div>\n'
    
    html += f'<div class="footer">Generated by 🕋 Auto Makah | {datetime.utcnow().strftime("%Y-%m-%d %H:%M")} UTC</div>\n</body></html>'
    
    path = _save_file(title, ".html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


# ─── Helpers ──────────────────────────────────────────────
def _save_file(title: str, ext: str) -> str:
    """Save to output/ directory with safe filename."""
    safe = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)[:60]
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe}_{timestamp}{ext}"
    out_dir = Path(__file__).parent.parent / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    return str(out_dir / filename)


# ─── AI-Powered Generator ─────────────────────────────────
async def ai_generate_document(
    doc_type: str,
    topic: str,
    detail: str = "",
) -> dict:
    """Use AI to generate document content, then render it."""
    from core.connectors import HybridRouter
    router = HybridRouter()

    # ─── Simple markdown-table prompt (GLM-5.2 is good at this) ───
    prompt = f"""Create a table about: {topic}
{detail}

Respond with ONLY a markdown table like this:
| Column1 | Column2 | Column3 |
|---------|---------|---------|
| Data1   | Data2   | Data3   |
| Data4   | Data5   | Data6   |

Include 5-8 realistic data rows. The table ONLY — no other text."""

    try:
        resp = await router.call(
            prompt,
            system_prompt="You are a data generator. Output ONLY a markdown table with realistic data. No introduction, no explanation.",
            max_tokens=2000
        )
    except Exception as e:
        return {"error": f"AI call failed: {str(e)}"}

    # ─── Parse markdown table ───
    if resp and resp.ok and resp.text:
        parsed = _parse_markdown_table(resp.text)
        if parsed and parsed["rows"]:
            return _render_document(doc_type, {
                "title": topic,
                "headers": parsed["headers"],
                "rows": parsed["rows"],
                "sections": [{"heading": topic, "body": resp.text}],
                "slides": [{"title": topic, "content": resp.text}],
            }, topic)
    
    # Fallback
    return _generate_fallback(doc_type, topic, detail)


def _parse_markdown_table(text: str) -> dict | None:
    """Parse a markdown table from AI output. Returns {headers, rows} or None."""
    import re
    lines = text.strip().split("\n")
    
    # Find table lines (lines with |)
    table_lines = [l.strip() for l in lines if l.strip().startswith("|") and l.strip().endswith("|")]
    
    if len(table_lines) < 2:
        return None
    
    def _parse_row(line: str) -> list:
        cells = [c.strip() for c in line.strip("|").split("|")]
        return [c for c in cells if c]  # remove empty
    
    headers = _parse_row(table_lines[0])
    
    # Skip separator line (|---|---|)
    rows = []
    for line in table_lines[1:]:
        row = _parse_row(line)
        if row and not all(c.replace("-", "").replace(" ", "") == "" for c in row):
            rows.append(row)
    
    if headers and rows:
        # Ensure all rows have same length as headers
        for i, row in enumerate(rows):
            while len(row) < len(headers):
                row.append("")
            rows[i] = row[:len(headers)]
        return {"headers": headers, "rows": rows}
    
    return None


def _generate_fallback(doc_type: str, topic: str, detail: str = "") -> dict:
    """Generate a simple document without AI."""
    return _render_document(doc_type, {
        "title": topic,
        "headers": ["Item", "Value"] if doc_type == "xlsx" else None,
        "rows": [["Topic", topic], ["Details", detail or "N/A"], ["Generated", datetime.utcnow().isoformat()]],
        "sections": [
            {"heading": topic, "body": detail or "Basic document generated by Auto Makah 🕋"}
        ],
        "slides": [
            {"title": topic, "content": detail or "Auto Makah 🕋 Generated Presentation"}
        ],
    }, topic)


def _render_document(doc_type: str, data: dict, topic: str) -> dict:
    """Render data to file."""
    title = data.get("title", topic)
    try:
        if doc_type == "xlsx":
            path = generate_xlsx(title, data.get("headers", ["Item", "Value"]), data.get("rows", []))
        elif doc_type == "docx":
            path = generate_docx(title, data.get("sections", []))
        elif doc_type == "pptx":
            path = generate_pptx(title, data.get("slides", []))
        elif doc_type == "pdf":
            path = generate_pdf_html(title, data.get("sections", []), "ar")
        else:
            return {"error": f"Unknown type: {doc_type}"}
        
        return {
            "path": path,
            "type": doc_type,
            "filename": os.path.basename(path),
            "title": title,
            "generated_at": datetime.utcnow().isoformat(),
        }
    except Exception as e:
        return {"error": f"File generation error: {str(e)}"}
