"""
Web Search + Document Export Agents — no AI needed
"""
import httpx, json, os

# ═══ Web Search (DuckDuckGo — no API key) ═══

async def web_search(query: str, max_results: int = 5) -> dict:
    """Search the web using DuckDuckGo Instant Answer API."""
    try:
        async with httpx.AsyncClient(timeout=15) as c:
            r = await c.get("https://api.duckduckgo.com/", params={
                "q": query, "format": "json", "no_html": 1, "skip_disambig": 1,
            })
            data = r.json()
            results = []
            # Abstract
            if data.get("AbstractText"):
                results.append({"title": data.get("AbstractSource", "DuckDuckGo"), "snippet": data["AbstractText"], "url": data.get("AbstractURL", "")})
            # Related topics
            for topic in data.get("RelatedTopics", [])[:max_results]:
                if isinstance(topic, dict) and "Text" in topic:
                    results.append({"title": topic.get("FirstURL", "").split("/")[-1].replace("_"," "), "snippet": topic["Text"], "url": topic.get("FirstURL", "")})
            return {"query": query, "results": results, "total": len(results)}
    except Exception as e:
        return {"query": query, "error": str(e), "results": []}

# ═══ Wikipedia Summary ═══

async def wikipedia_summary(topic: str, lang: str = "ar") -> dict:
    """Get Wikipedia summary."""
    try:
        async with httpx.AsyncClient(timeout=15) as c:
            r = await c.get(f"https://{lang}.wikipedia.org/api/rest_v1/page/summary/{topic}", headers={"User-Agent": "AutoMakah/1.0"})
            if r.status_code == 200:
                data = r.json()
                return {
                    "title": data.get("title"),
                    "summary": data.get("extract", "")[:2000],
                    "url": data.get("content_urls", {}).get("desktop", {}).get("page", ""),
                    "image": data.get("thumbnail", {}).get("source", ""),
                }
            return {"title": topic, "error": f"Wikipedia returned {r.status_code}"}
    except Exception as e:
        return {"error": str(e)}

# ═══ File Export ═══

def export_to_markdown(title: str, content: str) -> str:
    """Export analysis to markdown."""
    return f"# {title}\n\n---\n\n{content}\n\n---\n*Generated by Auto Makah*"

def export_to_html(title: str, content: str) -> str:
    """Export analysis to HTML."""
    return f"""<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head><meta charset="UTF-8"><title>{title}</title>
<style>body{{font-family:system-ui;max-width:800px;margin:40px auto;padding:0 20px;line-height:1.8;direction:rtl}}
h1{{color:#d4a017}}pre{{background:#1a1a2e;color:#e0e0e0;padding:16px;border-radius:8px;overflow-x:auto}}
</style></head>
<body><h1>{title}</h1><hr>{content.replace(chr(10), '<br>')}<hr><small>Auto Makah</small></body></html>"""

# ═══ Text Stats ═══

def text_stats(text: str) -> dict:
    """Analyze text statistics."""
    words = text.split()
    chars = len(text)
    lines = text.count('\n') + 1
    arabic_chars = sum(1 for c in text if '\u0600' <= c <= '\u06ff')
    return {
        "words": len(words),
        "characters": chars,
        "characters_no_spaces": len(text.replace(' ','').replace('\n','')),
        "lines": lines,
        "arabic_characters": arabic_chars,
        "arabic_percentage": round(arabic_chars / chars * 100, 1) if chars > 0 else 0,
        "reading_time_seconds": round(len(words) / 3 * 60),  # 3 words/sec for Arabic
    }
